In [94]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("pokemon.csv")

In [96]:
pd.set_option('display.max_columns', None)

In [4]:
df.sample(8) #sorteia dados aleatórios da base (o parâmetro indica quantos devem ser sorteados)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
261,262,III,Mightyena,Graena,dark,NaN,Bite Pokémon,50,50,1.0,...,Level,Mightyena,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mightyena gives obvious signals when it is pre...
483,484,IV,Palkia,Palkia,water,dragon,Spatial Pokémon,NaN,NaN,4.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It is said to live in a gap in the spatial dim...
30,31,I,Nidoqueen,Nidoqueen,poison,ground,Drill Pokémon,0,100,1.3,...,When Female,Nidoran♀,Level 16,Nidorina,Use Moonstone,Nidoqueen,NaN,NaN,NaN,Nidoqueen is better at defense than offense. W...
839,840,VIII,Applin,Kajitchu,grass,dragon,Apple Core Pokémon,50.2,49.8,0.2,...,Use Tart Apple,Flapple,Use Sweet Apple,Appletun,NaN,NaN,NaN,NaN,NaN,It spends its entire life inside an apple. It ...
479,480,IV,Uxie,Yuxie,psychic,NaN,Knowledge Pokémon,NaN,NaN,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Known as “The Being of Knowledge.” It is said ...
105,106,I,Hitmonlee,Sawamular,fighting,NaN,Kicking Pokémon,100,0,1.5,...,Attack > Defence at Level 20,Hitmonlee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This amazing Pokémon has an awesome sense of b...
140,141,I,Kabutops,Kabutops,rock,water,Shellfish Pokémon,88.14,11.86,1.3,...,Level,Kabutops,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kabutops slices its prey apart and sucks out t...
121,122,I,Mr. Mime,Barrierd,psychic,fairy,Barrier Pokémon,50.2,49.8,1.3,...,Level up while knowing Mimic,Mr.mime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The broadness of its hands may be no coinciden...

In [29]:
df.info()
#todos os dados com 'object' são palavras
#todos os dados em 'float64' ou 'int64' são números

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 55 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   national_number     898 non-null    int64
 1   gen                 898 non-null    object
 2   english_name        898 non-null    object
 3   japanese_name       898 non-null    object
 4   primary_type        898 non-null    object
 5   secondary_type      469 non-null    object
 6   classification      898 non-null    object
 7   percent_male        776 non-null    object
 8   percent_female      776 non-null    object
 9   height_m            898 non-null    float64
 10  weight_kg           898 non-null    float64
 11  capture_rate        898 non-null    object
 12  base_egg_steps      898 non-null    int64
 13  hp                  898 non-null    int64
 14  attack              898 non-null    int64
 15  defense             898 non-null    int64
 16  sp_attack           898 non-null    int64
 17  sp_defense          898 non-null    int64
 18  speed               898 non-null    int64
 19  abilities_0         898 non-null    object
 20  abilities_1         495 non-null    object
 21  abilities_2         3 non-null      object
 22  abilities_hidden    763 non-null    object
 23  against_normal      898 non-null    float64
 24  against_fire        898 non-null    float64
 25  against_water       898 non-null    float64
 26  against_electric    898 non-null    float64
 27  against_grass       898 non-null    float64
 28  against_ice         898 non-null    float64
 29  against_fighting    898 non-null    float64
 30  against_poison      898 non-null    float64
 31  against_ground      898 non-null    float64
 32  against_flying      898 non-null    float64
 33  against_psychict    898 non-null    float64
 34  against_bug         898 non-null    float64
 35  against_rock        898 non-null    float64
 36  against_ghost       898 non-null    float64
 37  against_dragon      898 non-null    float64
 38  against_dark        898 non-null    float64
 39  against_steel       898 non-null    float64
 40  against_fairy       898 non-null    float64
 41  is_sublegendary     898 non-null    int64
 42  is_legendary        898 non-null    int64
 43  is_mythical         898 non-null    int64
 44  evochain_0          898 non-null    object
 45  evochain_1          728 non-null    object
 46  evochain_2          728 non-null    object
 47  evochain_3          335 non-null    object
 48  evochain_4          332 non-null    object
 49  evochain_5          19 non-null     object
 50  evochain_6          19 non-null     object
 51  gigantamax          31 non-null     object
 52  mega_evolution      46 non-null     object
 53  mega_evolution_alt  2 non-null      object
 54  description         898 non-null    object
dtypes: float64(20), int64(11), object(24)
memory usage: 301.7+ KB

In [27]:
#COLOCANDO OS DADOS EM FORMATO DE PORCENTAGEM

k=776/898
#Use str. format() to format a number as a percentage
#a_number = 0.20.
#percentage = "{:.0%}". format(a_number)
#print(percentage)

print("{:.0%}".format(k), "of the pokemons in df have a gender")

86% of the pokemons in df have a gender

In [28]:
k

0.8641425389755011

In [35]:
df.describe()
#mostra dados como quantidade, média, desvio padrão ('std')
#os dados em 25%, 50% e 75% indicam os quartis que...
#...são a maneira pela qual os dados estão distribuidos...
#...em ordem crescente: o dado em 25% indica o primeiro quarto; o dado em 50% apresenta...
#...o dado que está exatamente no meio; e o dado em 75% apresenta o número que consta em...
#...3/4 da sequência crescente
#Isso indica, por exemplo que metade dos pokemons tem vida em até 65 pontos!
#Ou que 1/4 dos pokemons tem pontos de vida iguais ou menores que 50.  
#Através desses dados podemos ver também que entre o primeiro quartil (25%)
#e o próximo (50%), temos outro quarto que tem entre 50 e 65 pontos de vida

,national_number,height_m,weight_kg,base_egg_steps,hp,attack,defense,sp_attack,sp_defense,speed,...,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,is_sublegendary,is_legendary,is_mythical
count,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,...,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.00000,898.000000,898.000000,898.000000
mean,449.500000,1.185969,63.970045,7544.587973,69.031180,76.544543,71.886414,69.681514,69.876392,65.949889,...,0.999165,1.245546,0.994432,0.972717,1.057628,0.984131,1.08157,0.050111,0.022272,0.022272
std,259.374568,1.234222,119.430298,7101.313608,26.213707,29.665559,29.536184,29.372609,27.012142,28.456596,...,0.609120,0.702248,0.553163,0.365120,0.441639,0.497022,0.53157,0.218296,0.147648,0.147648
min,1.000000,0.100000,0.100000,1280.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,...,0.250000,0.250000,0.000000,0.000000,0.250000,0.250000,0.25000,0.000000,0.000000,0.000000
25%,225.250000,0.500000,8.500000,5120.000000,50.000000,55.000000,50.000000,46.250000,50.000000,45.000000,...,0.500000,1.000000,1.000000,1.000000,1.000000,0.500000,1.00000,0.000000,0.000000,0.000000
50%,449.500000,1.000000,27.000000,5120.000000,65.000000,75.000000,67.000000,65.000000,65.000000,65.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000
75%,673.750000,1.500000,65.000000,6400.000000,80.000000,95.000000,90.000000,90.000000,85.000000,85.000000,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000
max,898.000000,20.000000,999.900000,30720.000000,255.000000,181.000000,230.000000,173.000000,230.000000,200.000000,...,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,4.00000,1.000000,1.000000,1.000000

In [10]:
#Vídeo: https://www.youtube.com/watch?v=vUKlxXpvt3I
#PAROU EM 29:55
df.shape
l, c=df.shape #perceba que cada dado fica alocado seguindo a ordem que foi 
#criada, isto é, linhas vai para 'l' e colunas vai para 'c'

In [13]:
print("O dataframe de pokemon possui", l, "linhas e", c, "colunas.")

O dataframe de pokemon possui 898 linhas e 55 colunas.

In [17]:
df["hp"].head(8)>13

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: hp, dtype: bool

In [22]:
life_pokemon=df["hp"]
nome_en=df["english_name"]

In [19]:
life_pokemon.head() #Não preciso chamar mais o dataframe, para essa coluna

0    45
1    60
2    80
3    39
4    58
Name: hp, dtype: int64

In [23]:
type(nome_en)

pandas.core.series.Series

In [29]:
nomeenjptipo=df[["english_name", "japanese_name", "primary_type", "secondary_type"]]
#é possível selecionar mais de uma coluna
#fazendo um mini dataframe

In [30]:
nomeenjptipo.sample(10)

    english_name japanese_name primary_type secondary_type
490      Darkrai       Darkrai         dark            NaN
372    Salamence     Bohmander       dragon         flying
818      Skwovet   Hoshigarisu       normal            NaN
223    Octillery       Okutank        water            NaN
296     Hariyama    Hariteyama     fighting            NaN
771   Type: Null    Type: Null       normal            NaN
406     Roserade      Roserade        grass         poison
473    Porygon-Z     Porygon-z       normal            NaN
674      Pangoro       Goronda     fighting           dark
238       Elekid        Elekid     electric            NaN

In [33]:
type(nomeenjptipo)

pandas.core.frame.DataFrame

In [35]:
darkpoke=df[df["primary_type"] == 'dark'] #seleciona todos os pokemons de tipo dark

In [41]:
darkpoke.shape #36 linhas e 55 colunas
#Você pode se desafiar e criar uma função que crie uma frase automaticamente 
#para mostrar quantas linhas/colunas tem no dataframe

(36, 55)

In [43]:
darkpoke.sample()

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
558,559,V,Scraggy,Zuruggu,dark,fighting,Shedding Pokémon,50.2,49.8,0.6,...,Level,Scrafty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"If it locks eyes with you, watch out! Nothing ..."

In [40]:
strenght=df[["english_name", 'against_water', 'against_dark', 'against_fire', 'against_ghost']]
strenght.shape

(898, 5)

In [54]:
fraco_fant=strenght[strenght["against_ghost"]>1]

In [55]:
fraco_fant.head(12) #cinco primeiros pokemons da base 'strenght' que são mais fracos 
#contra o tipo fantasma

    english_name  against_water  against_fire  against_ghost
719        Hoopa            1.0           1.0            4.0
791       Lunala            1.0           1.0            4.0

In [46]:
fraco_agua_fogo_dark=strenght[(strenght["against_dark"]>0.75) & (strenght["against_fire"]>2)]

In [49]:
fraco_agua_fogo_dark #selecionei os pokemons fracos contra fogo e páreos contra
#tipo 'dark'

#Sinais utilizáveis
#& -> <<e>> binário
#| -> <<ou>> binário

    english_name  against_water  against_dark  against_fire  against_ghost
45         Paras            0.5           1.0           4.0            1.0
46      Parasect            0.5           1.0           4.0            1.0
204   Forretress            1.0           1.0           4.0            1.0
211       Scizor            1.0           1.0           4.0            1.0
412     Wormadam            0.5           1.0           4.0            1.0
458       Snover            0.5           1.0           4.0            1.0
459    Abomasnow            0.5           1.0           4.0            1.0
539     Sewaddle            0.5           1.0           4.0            1.0
540     Swadloon            0.5           1.0           4.0            1.0
541     Leavanny            0.5           1.0           4.0            1.0
588   Escavalier            1.0           1.0           4.0            1.0
596    Ferroseed            0.5           1.0           4.0            1.0
597   Ferrothorn            0.5           1.0           4.0            1.0
631       Durant            1.0           1.0           4.0            1.0
648     Genesect            1.0           1.0           4.0            1.0
797      Kartana            0.5           1.0           4.0            1.0
871         Snom            1.0           1.0           4.0            1.0
872     Frosmoth            1.0           1.0           4.0            1.0

In [10]:
at_def=df[["english_name", "attack", "defense"]] #sempre colocar dois colchetes: aqui vc está armazenando uma
#lista com diferentes colunas

In [16]:
at_def[(at_def["attack"]>100) & (at_def["defense"]<105)].describe()

           attack     defense
count  130.000000  130.000000
mean   119.969231   77.276923
std     11.981859   15.317829
min    101.000000   37.000000
25%    110.000000   65.000000
50%    120.000000   78.500000
75%    125.000000   90.000000
max    165.000000  103.000000

In [17]:
at_def[(at_def["attack"]>125) & (at_def["defense"]<105)] #agora eu vou selecionar apenas o 3º quartil (75%)

     english_name  attack  defense
67        Machamp     130       80
135       Flareon     130       60
148     Dragonite     134       95
211        Scizor     130      100
216      Ursaring     130       75
249         Ho-Oh     130       90
285       Breloom     130       80
288       Slaking     160      100
358         Absol     130       60
372     Salamence     135       80
383      Rayquaza     150       90
385        Deoxys     150       50
408     Rampardos     165       60
444      Garchomp     130       95
472     Mamoswine     130       80
529     Excadrill     135       60
533    Conkeldurr     140       95
554    Darmanitan     140       55
566      Archeops     140       65
611       Haxorus     147       90
613       Beartic     130       80
638     Terrakion     129       90
645        Kyurem     130       90
715       Xerneas     131       95
716       Yveltal     131       95
739  Crabominable     132       77
780      Dhelmise     131      100
794     Pheromosa     137       37
805   Blacephalon     127       53
864    Sirfetch'd     135       95
878    Copperajah     130       69
891       Urshifu     130      100

In [33]:
df[877:879]["primary_type"]

877    steel
878    steel
Name: primary_type, dtype: object

In [71]:
flt_mega=df[df["mega_evolution"].notna()]

In [65]:
flt_mega2=flt_mega[flt_mega["english_name", "mega_evolution", "primary_type"]]

KeyError: ('english_name', 'mega_evolution', 'primary_type')

In [78]:
flt_mega[["english_name", "mega_evolution", "primary_type"]] #selecionei 3 colunas dentro da variável 
#onde eu coloquei o método .notna(); com ele, é possível ver apenas as colunas onde há 
#algum dado

    english_name    mega_evolution primary_type
2       Venusaur     Mega Venusaur        grass
5      Charizard  Mega Charizard X         fire
8      Blastoise    Mega Blastoise        water
14      Beedrill     Mega Beedrill          bug
17       Pidgeot      Mega Pidgeot       normal
64      Alakazam     Mega Alakazam      psychic
79       Slowbro      Mega Slowbro        water
93        Gengar       Mega Gengar        ghost
114   Kangaskhan   Mega Kangaskhan       normal
126       Pinsir       Mega Pinsir          bug
129     Gyarados     Mega Gyarados        water
141   Aerodactyl   Mega Aerodactyl         rock
149       Mewtwo     Mega Mewtwo X      psychic
180     Ampharos     Mega Ampharos     electric
207      Steelix      Mega Steelix        steel
211       Scizor       Mega Scizor          bug
213    Heracross    Mega Heracross          bug
228     Houndoom     Mega Houndoom         dark
247    Tyranitar    Mega Tyranitar         rock
253     Sceptile     Mega Sceptile        grass
256     Blaziken     Mega Blaziken         fire
259     Swampert     Mega Swampert        water
281    Gardevoir    Mega Gardevoir      psychic
301      Sableye      Mega Sableye         dark
302       Mawile       Mega Mawile        steel
305       Aggron       Mega Aggron        steel
307     Medicham     Mega Medicham     fighting
309    Manectric    Mega Manectric     electric
318     Sharpedo     Mega Sharpedo        water
322     Camerupt     Mega Camerupt         fire
333      Altaria      Mega Altaria       dragon
353      Banette      Mega Banette        ghost
358        Absol        Mega Absol         dark
361       Glalie       Mega Glalie          ice
372    Salamence    Mega Salamence       dragon
375    Metagross    Mega Metagross        steel
379       Latias       Mega Latias       dragon
380       Latios       Mega Latios       dragon
383     Rayquaza     Mega Rayquaza       dragon
427      Lopunny      Mega Lopunny       normal
444     Garchomp     Mega Garchomp       dragon
447      Lucario      Mega Lucario     fighting
459    Abomasnow    Mega Abomasnow        grass
474      Gallade      Mega Gallade      psychic
530       Audino       Mega Audino       normal
718      Diancie      Mega Diancie         rock

In [82]:
ataq=flt_mega[["english_name", "mega_evolution", "primary_type", "attack"]]
ataq["english_name", "attack"]

KeyError: ('english_name', 'attack')

In [85]:
df.iloc[878] #posso obter os dados completos de uma única linha com iloc
#ele só pode ser utilizado pra índice, não por nome (por isso que 
#a função tem 'i' no nome)

national_number                                                     879
gen                                                                VIII
english_name                                                 Copperajah
japanese_name                                                  Daioudou
primary_type                                                      steel
secondary_type                                                      NaN
classification                                       Copperderm Pokémon
percent_male                                                       50.2
percent_female                                                     49.8
height_m                                                              3
weight_kg                                                           650
capture_rate                                                         90
base_egg_steps                                                     6400
hp                                                                  122
attack                                                              130
defense                                                              69
sp_attack                                                            80
sp_defense                                                           69
speed                                                                30
abilities_0                                                 Sheer Force
abilities_1                                                         NaN
abilities_2                                                         NaN
abilities_hidden                                            Heavy Metal
against_normal                                                      0.5
against_fire                                                          2
against_water                                                         1
against_electric                                                      1
against_grass                                                       0.5
against_ice                                                         0.5
against_fighting                                                      2
against_poison                                                        0
against_ground                                                        2
against_flying                                                      0.5
against_psychict                                                    0.5
against_bug                                                         0.5
against_rock                                                        0.5
against_ghost                                                         1
against_dragon                                                      0.5
against_dark                                                          1
against_steel                                                       0.5
against_fairy                                                       0.5
is_sublegendary                                                       0
is_legendary                                                          0
is_mythical                                                           0
evochain_0                                                       Cufant
evochain_1                                                        Level
evochain_2                                                   Copperajah
evochain_3                                                          NaN
evochain_4                                                          NaN
evochain_5                                                          NaN
evochain_6                                                          NaN
gigantamax                                        Gigantamax Copperajah
mega_evolution                                                      NaN
mega_evolution_alt                                                  NaN
description           They came over from another region long ago an...
Name: 878, dtype: object

In [100]:
pd.set_option('max_colwidth', None) #essa função permite que os dados das colunas sejam vistos 
#na íntegra; saiba mais:https://abre.ai/integra-coluna-python

df.iloc[557:560][["english_name","description"]] #esse é o formato para colocar mais de uma
#coluna; nesse caso vc tem que criar uma lista de colunas

,english_name,description
557,Crustle,This highly territorial Pokémon prefers dry climates. It won’t come out of its boulder on rainy days.
558,Scraggy,"If it locks eyes with you, watch out! Nothing and no one is safe from the reckless headbutts of this troublesome Pokémon."
559,Scrafty,"As halfhearted as this Pokémon’s kicks may seem, they pack enough power to shatter Conkeldurr’s concrete pillars."

In [105]:
#vc pode também fazer seleção de linhas e de colunas ao mesmo tempo
pd.set_option('max_colwidth', None)
df.iloc[100:121, [0,2,5,10,23,25]]

,national_number,english_name,secondary_type,weight_kg,against_normal,against_water
100,101,Electrode,NaN,66.6,1.0,1.0
101,102,Exeggcute,psychic,2.5,1.0,0.5
102,103,Exeggutor,psychic,120.0,1.0,0.5
103,104,Cubone,NaN,6.5,1.0,2.0
104,105,Marowak,fire,45.0,1.0,2.0
105,106,Hitmonlee,NaN,49.8,1.0,1.0
106,107,Hitmonchan,NaN,50.2,1.0,1.0
107,108,Lickitung,NaN,65.5,1.0,1.0
108,109,Koffing,NaN,1.0,1.0,1.0
109,110,Weezing,poison,9.5,1.0,1.0
110,111,Rhyhorn,rock,115.0,0.5,4.0
111,112,Rhydon,rock,120.0,0.5,4.0
112,113,Chansey,NaN,34.6,1.0,1.0
113,114,Tangela,NaN,35.0,1.0,0.5
114,115,Kangaskhan,NaN,80.0,1.0,1.0
115,116,Horsea,NaN,8.0,1.0,0.5
116,117,Seadra,NaN,25.0,1.0,0.5
117,118,Goldeen,NaN,15.0,1.0,0.5
118,119,Seaking,NaN,39.0,1.0,0.5
119,120,Staryu,NaN,34.5,1.0,0.5
120,121,Starmie,psychic,80.0,1.0,0.5

In [110]:
df.iloc[32:75:5] #dados até 75 pulando de 5 em 5!!!!

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,weight_kg,capture_rate,base_egg_steps,hp,attack,defense,sp_attack,sp_defense,speed,abilities_0,abilities_1,abilities_2,abilities_hidden,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychict,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,is_sublegendary,is_legendary,is_mythical,evochain_0,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
32,33,I,Nidorino,Nidorino,poison,NaN,Poison Pin Pokémon,100,0,0.9,19.5,120,5120,61,72,57,55,55,65,Poison Point,Rivalry,NaN,Hustle,1.0,1.0,1.0,1.0,0.50,1.0,0.50,0.5,2.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,0.5,0,0,0,Egg,When Male,Nidoran♂,Level 16,Nidorino,Use Moonstone,Nidoking,NaN,NaN,NaN,"With a horn that’s harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone."
37,38,I,Ninetales,Kyukon,fire,ice,Fox Pokémon,24.9,75.1,1.1,19.9,75,5120,73,76,75,81,100,100,Flash Fire,NaN,NaN,Snow Cloak- Snow Warning,1.0,0.5,2.0,1.0,0.50,0.5,1.00,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0,0,0,Vulpix,Use Fire Stone,Ninetales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"It is said to live 1,000 years, and each of its tails is loaded with supernatural powers."
42,43,I,Oddish,Nazonokusa,grass,poison,Weed Pokémon,50.2,49.8,0.5,5.4,255,5120,45,50,55,75,65,30,Chlorophyll,NaN,NaN,Run Away,1.0,2.0,0.5,0.5,0.25,2.0,0.50,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0,0,0,Oddish,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,"If exposed to moonlight, it starts to move. It roams far and wide at night to scatter its seeds."
47,48,I,Venonat,Kongpang,bug,poison,Insect Pokémon,50,50,1.0,30.0,190,5120,60,55,50,40,55,45,Compound Eyes,Tinted Lens,NaN,Run Away,1.0,2.0,1.0,1.0,0.25,1.0,0.25,0.5,1.0,2.0,2.0,0.5,2.0,1.0,1.0,1.0,1.0,0.5,0,0,0,Venonat,Level,Venomoth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Its large eyes act as radar. In a bright place, you can see that they are clusters of many tiny eyes."
52,53,I,Persian,Persian,normal,dark,Classy Cat Pokémon,50.2,49.8,1.0,32.0,90,5120,65,70,60,65,65,115,Limber,Technician,NaN,Unnerve,1.0,1.0,1.0,1.0,1.00,1.0,2.00,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0,0,0,Meowth,Level,Persian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Getting this prideful Pokémon to warm up to you takes a lot of effort, and it will claw at you the moment it gets annoyed."
57,58,I,Growlithe,Gardie,fire,NaN,Puppy Pokémon,75.49,24.51,0.7,19.0,190,5120,55,70,45,70,50,60,Intimidate,Flash Fire,NaN,Justified,1.0,0.5,2.0,1.0,0.50,0.5,1.00,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0,0,0,Growlithe,Use Fire Stone,Arcanine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes.
62,63,I,Abra,Casey,psychic,NaN,Psi Pokémon,75.49,24.51,0.9,19.5,200,5120,25,20,15,105,55,90,Synchronize,Inner Focus,NaN,Magic Guard,1.0,1.0,1.0,1.0,1.00,1.0,0.50,1.0,1.0,1.0,0.5,2.0,1.0,2.0,1.0,2.0,1.0,1.0,0,0,0,Abra,Level,Kadabra,Trade,Alakazam,NaN,NaN,NaN,NaN,NaN,This Pokémon uses its psychic powers while it sleeps. The contents of Abra’s dreams affect the powers that the Pokémon wields.
67,68,I,Machamp,Kairiky,fighting,NaN,Superpower Pokémon,75.49,24.51,1.6,130.0,45,5120,90,130,80,65,85,55,Guts,No Guard,NaN,Steadfast,1.0,1.0,1.0,1.0,1.00,1.0,1.00,1.0,1.0,2.0,2.0,0.5,0.5,1.0,1.0,0.5,1.0,2.0,0,0,0,Machop,Level,Machoke,Trade,Machamp,NaN,NaN,Gigantamax Machamp,NaN,NaN,It quickly swings its four arms to rock its opponents with ceaseless punches and chops from all angles.
72,73,I,Tentacruel,Dokukurage,water,poison,Jellyfish Pokémon,50.2,49.8,1.6,55.0,60,5120,80,70,65,80,120,100,Clear Body,Liquid Ooze,NaN,Rain Dish,1.0,0.5,0.5,2.0,1.00,0.5,0.50,0.5,2.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,0.5,0.5,0,0,0,Tentacool,Level,Tentacruel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"When the red orbs on Tentacruel’s head glow brightly, watch out. The Pokémon is about to fire off a burst of ultrasonic waves."

In [113]:
df.loc[878,"english_name"] #aqui eu posso chamar por strings (nomes)

'Copperajah'